### ISSUE TITLE
Definitions and Comments Language Color

### ISSUE THREAD

**Issue by Pantyhose-X** [toaq/toadua#34]
example：
**Gı hóeı ba.**
Toaq: `Gı hóeı ba`   Toaq always uses red Definitions.
English: `May the morning be good` Other colors Definitions 
Russian: `Пусть утро будет добрым` Other colors Definitions

**Comment by uakci** [comment]
We already do this for Toaq that is properly marked up with double asterisks (all Toaq text should be enclosed with `**…**`, and if it is, it lights up pink and becomes clickable). As for other languages, I believe your suggestion is redundant to scopes (and the “show words in xxx scope only” switch in the top bar of the UI).
