### ISSUE TITLE
Searching `head:` doesn't count raku-initial m as a consonant

### ISSUE THREAD

**Issue by ijo-isi** [toaq/toadua#41]
When searching Toadua with `head:`, using a `C` doesn't match the letter m, even when the m appears at the start of a raku.

For example, searching `head:Cameı` doesn't yield the definition of mameı, even though `head:mameı` does.

**Comment by uakci** [comment]
Thanks for the report, it appears that we’ve completely missed updating the formatting/parsing routines for Delta. (A similar issue happens with tone numbers misinteracting with **m**-final syllables, and I think the two issues are related but I can’t be sure.)
