### ISSUE TITLE
Heads like "123" are considered exact matches for queries like "scope:en"

### ISSUE THREAD

**Issue by lynn** [toaq/toadua#53]
[This entry](https://toadua.uakci.pl/##rqhd9AIma) gets a lot of relevance points and ends up at the top in a query like `scope:en` or ` ` (just a space). I think this is because `deburr` turns the head into `[]` which is an exact match for the text in the query (i.e. nothing).

**Comment by uakci** [comment]
deburr would turn `123` into `["123"]` I reckon, but I can’t be sure. That said the query ` ` would score `123` high because it matches all 0 of 0 search terms and is relatively short, I think. Needs debugging.

**Comment by lynn** [comment]
Fixed in 9a79db61451c38c7cce84c695eea23e634036e8f
